/** Local mock catalog, stories, and assessment data. */
export type Product={slug:string;name:string;subtitle:string;form:'Wearable'|'Stationary'|'Carryable';energy:string;price:number;description:string;color:string};
export const products:Product[]=[
{slug:'rose-thread-bracelet',name:'Rose Thread Bracelet',subtitle:'Build · Magnetism · Ascent',form:'Wearable',energy:'Connection',price:78,description:'A rose quartz wearable, traditionally associated with gentle connection and a reminder of tenderness.',color:'#a0616f'},
{slug:'obsidian-anchor',name:'Obsidian Anchor',subtitle:'Hold · Listen · Return',form:'Wearable',energy:'Grounding',price:82,description:'A dark stone bracelet traditionally associated with steady presence and a reminder to return to your center.',color:'#202328'},
{slug:'citrine-orbit',name:'Citrine Orbit',subtitle:'Gather · Move · Open',form:'Wearable',energy:'Flow',price:76,description:'A warm citrine bracelet that symbolizes movement and is a reminder to notice natural flow.',color:'#ba8938'},
{slug:'clear-field',name:'Clear Field Bracelet',subtitle:'See · Soften · Align',form:'Wearable',energy:'Clarity',price:74,description:'A clear quartz wearable traditionally associated with reflection and a reminder of quiet clarity.',color:'#d9d5c8'},
{slug:'lunar-keyhole',name:'Lunar Keyhole Thangka',subtitle:'A Stationary Portal',form:'Stationary',energy:'Clarity',price:168,description:'A mineral-pigment thangka, a stationary portal for your space that symbolizes stillness.',color:'#263d62'},
{slug:'golden-script',name:'Golden Script Talisman',subtitle:'A Carryable Symbol',form:'Carryable',energy:'Flow',price:30,description:'A carryable symbol inspired by Taoist visual culture, a reminder of your chosen intention.',color:'#c9a96e'}];
export const questions=[
['When the room gets quiet, you reach for…',['a familiar voice','a grounded routine','an open window','a blank page']],['Your ideal beginning feels…',['shared','steady','unplanned','clear']],['A color that follows you today…',['rose','obsidian','amber','pearl']],['You want more room for…',['connection','presence','movement','perspective']],['The Thread you notice first is…',['warm','low','moving','vertical']],['At 11:11, you would…',['send a note','stand still','take a walk','make a list']],['Choose a landscape…',['a garden','a mountain','a river','a moonlit plain']],['Your field belongs…',['on the wrist','on a wall','in a pocket','across all three']],['You most want to meet it…',['while wearing','in your space','on the move','as a set']],['The final form feels…',['Wearable','Stationary','Carryable','Complete']]
] as const;
